imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: "%kernel.root_dir%/data/data.db3"
        # path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    encryption: ssl
#    auth_mode:  login
#    host:       smtp.gmail.com
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    port:      "%mailer_port%"
    transport: "%mailer_transport%"
    sender_address : "%mailer_from%"

# Requirejs
hearsay_require_js:
    require_js_src:      //cdnjs.cloudflare.com/ajax/libs/require.js/2.1.14/require.min.js #js/require.js
    initialize_template: HearsayRequireJSBundle::initialize.html.twig
    base_url:            js #папка в которую будут собираться наши, не полностью обработанные,  скрипты в «дев» версии в каталоге «web».
    base_dir:            %kernel.root_dir%/../src/Tommy/Pymnt/MainBundle/Resources/assets/js # Required #путь к папке со скриптами в бандле

    #пути к основным модулям и скриптам для requirejs.config()
    #для внешних библиотек не забываем указывать «external: true»
    paths:
        main:
            location: @TommyPymntMainBundle/Resources/assets/js/main
        jquery:
            location: //ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min
            external: true
        bootstrap:
            location: //maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min
            external: true
    shim:
        # Prototype
        name:
            deps:    [jquery]
            exports: ~
    options:
        # Prototype
        name:
            value: ~ # Required
    optimizer:
        path:                    %kernel.root_dir%/../node_modules/requirejs/bin/r.js # Required
        hide_unoptimized_assets: false #true - для продакшена прячем все не оптимизированные файлы для папки web
        almond_path:             ~
        exclude:                 []
#        modules:
            # Prototype
   #         name:
 #               include: ~
  #              exclude: ~
#        options:
            # Prototype
 #           name:
  #              value: ~ # Required
        timeout: 120

# Assetic Configuration
assetic:
    debug: %kernel.debug%
    use_controller:
        enabled: %kernel.debug%
        profiler: false
    #node: %nodejs.executable.path% #default value must work
    filters:
        scss: ~
  #      sass: ~

# Auto load templates with rest
sensio_framework_extra:
    view:
        annotations: false
fos_rest:
    view:
        view_response_listener: true