security:
    encoders:
        Tommy\Pymnt\MainBundle\Entity\User:
            algorithm: bcrypt
            cost: 12
    providers:
        main_provider:
            entity: { class: TommyPymntMainBundle:User, property: email }
    firewalls:
        secured_area:
            pattern:   ^/cabinet
            anonymous: ~
            form_login:
                login_path: login
                check_path: login_check
            logout:
                path:   /cabinet/logout
                target: /

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        default:
            anonymous: ~
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/cabinet, roles: ROLE_USER }
