login:
    path:     /login
    defaults: { _controller: TommyPymntMainBundle:Default:login }
login_check:
    path: /login_check
logout:
    path: /logout

tommy_pymnt_main_homepage:
    path:     /
    defaults: { _controller: TommyPymntMainBundle:Default:index }
