parameters:
#    tommy_pymnt_main.example.class: Tommy\Pymnt\MainBundle\Example

services:
#    tommy_pymnt_main.example:
#        class: %tommy_pymnt_main.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
